version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports: 
      - '5432:5432'

  todolist:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todolist?schema=public
    depends_on:
      - db
    ports:
      - '3000:3000'